# Generated by Django 2.2 on 2019-05-07 18:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0002_auto_20190507_1650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnimalsTableMetadata',
            new_name='AnimalTableMetadata',
        ),
    ]
