# Generated by Django 2.2 on 2019-05-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_auto_20190509_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='adoption_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='fostering_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='sheltering_background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='for_adoption',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('to_be', 'To be'), ('hold', 'Hold')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='joined_reason',
            field=models.CharField(blank=True, choices=[('stray', 'Stray'), ('rescue', 'Rescue'), ('neglected', 'Neglected'), ('transfer', 'Transfer'), ('medical', 'Medical'), ('temporary', 'Temporary'), ('other', 'Other')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='leave_reason',
            field=models.CharField(blank=True, choices=[('adoption', 'Adoption'), ('foster', 'Foster'), ('medical', 'Medical'), ('temporary', 'Temporary'), ('death', 'Death'), ('transfer', 'Transfer'), ('other', 'Other')], max_length=9, null=True),
        ),
    ]
