# Generated by Django 2.2 on 2019-05-06 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_auto_20190503_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalHealthCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(choices=[('vaccination', 'Vaccination'), ('medicine', 'Medicine'), ('grooming', 'Grooming'), ('boarding', 'Boarding'), ('other', 'Other')], max_length=11)),
                ('note', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('animal_health', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.AnimalHealth')),
            ],
        ),
        migrations.RemoveField(
            model_name='animal',
            name='microchip_number',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='tag_number',
        ),
        migrations.AddField(
            model_name='animal',
            name='chip_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='chip_producer',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='tag_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='animalappearance',
            name='coat_type',
            field=models.CharField(blank=True, choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long'), ('hairless', 'Hairless')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='animalowner',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='animalowner',
            name='state',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='animalowner',
            name='zip_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='accommodation',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('townhouse', 'Townhouse'), ('house', 'House'), ('villa', 'Villa'), ('farm', 'Farm'), ('other', 'Other')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animals_friendly',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('only_small_animals', 'Only Small Animals'), ('only_big_animals', 'Only Big Animals'), ('unknown', 'Unknown')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='cats_friendly',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('only_females', 'Only Females'), ('only_males', 'Only Males'), ('unknown', 'Unknown')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='dogs_friendly',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('only_females', 'Only Females'), ('only_males', 'Only Males'), ('unknown', 'Unknown')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='for_foster',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('to_be', 'To be'), ('hold', 'Hold')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='humans_friendly',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('only_females', 'Only Females'), ('only_males', 'Only Males'), ('unknown', 'Unknown')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='kids_friendly',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('only_females', 'Only females'), ('only_males', 'Only males'), ('only_males', 'Only young kids'), ('only_males', 'Only old kids'), ('only_males', 'Both young & old'), ('unknown', 'Unknown')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='animalowner',
            name='owner_status',
            field=models.CharField(blank=True, choices=[('existing_owner', 'Existing Owner'), ('previous_owner', 'Previous Owner'), ('foster', 'Foster'), ('adopter', 'Adopter'), ('no_owner', 'No Owner'), ('other', 'Other')], max_length=14, null=True),
        ),
        migrations.DeleteModel(
            name='AnimalHealthVaccination',
        ),
    ]
