# Generated by Django 2.2 on 2019-05-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_auto_20190509_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='photoId',
            field=models.ImageField(blank=True, null=True, upload_to='animals/photo_ids'),
        ),
    ]
