# Generated by Django 2.2 on 2019-05-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_animal_photoid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='photoId',
            new_name='photo_id',
        ),
    ]
