# Generated by Django 2.2 on 2019-05-10 13:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_auto_20190510_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaltablemetadata',
            name='columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), default=list, max_length=8, size=None),
        ),
    ]
