# Generated by Django 2.2 on 2019-05-10 14:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_auto_20190510_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaltablemetadata',
            name='columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32), default=list, size=None),
        ),
    ]
