# Generated by Django 2.2 on 2019-05-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_auto_20190510_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animalowner',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
