# Generated by Django 2.2 on 2019-05-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_auto_20190512_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='personality_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
