# Generated by Django 2.2 on 2019-05-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0012_auto_20190512_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalhealth',
            name='sterilized',
            field=models.CharField(blank=True, choices=[('spayed', 'Spayed'), ('neutered', 'Neutered'), ('no', 'No')], max_length=8, null=True),
        ),
    ]
