# Generated by Django 2.2 on 2019-05-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0013_auto_20190513_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='for_adoption',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('to_be', 'To be'), ('hold', 'Hold')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='for_foster',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('to_be', 'To be'), ('hold', 'Hold')], max_length=5, null=True),
        ),
    ]
