# Generated by Django 2.2 on 2019-04-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190419_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('helper', 'Helper'), ('admin', 'Admin'), ('super_admin', 'Super Admin'), ('django_admin', 'Django Admin')], default='helper', max_length=12),
        ),
    ]
