# Generated by Django 2.2 on 2019-04-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_profile_image'),
        ('users', '0008_user_user_type'),
    ]

    operations = [
    ]
