# Generated by Django 2.2 on 2019-04-25 11:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_20190422_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('helper', 'Assistant'), ('admin', 'Admin'), ('super_admin', 'Super Admin'), ('django_admin', 'Django Admin')], default='helper', max_length=12),
        ),
    ]
