# Generated by Django 2.2 on 2019-05-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20190510_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='schedule_friday',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='schedule_monday',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='schedule_saturday',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='schedule_sunday',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='schedule_thursday',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='schedule_tuesday',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='schedule_wednesday',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
